name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
#  test:  TODO: Add tests
#    if: github.ref_name == 'main' || contains(github.event.head_commit.message, '[run-test]')
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@main
#      - name: Set up Python 3.10
#        uses: actions/setup-python@main
#        with:
#          python-version: "3.10"
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 pytest pytest-asyncio pytest-aiohttp
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#
#      - name: Lint with flake8
#        run: |
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#      - name: Test with pytest
#        run: |
#          pytest

  release:
    if: github.event_name == 'push' && github.ref_name == 'main'
#    needs: test
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Python Semantic Release
        run: |
          pip install python-semantic-release
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          semantic-release publish -D commit_author="sudip-roy <sudiproy20yo@gmail.com>"
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
